# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sgpt < Formula
  desc "Go clone of shell_gpt command. A command-line productivity tool powered by AI large language models (LLMs)."
  homepage "https://github.com/hirosassa/sgpt"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hirosassa/sgpt/releases/download/v0.0.2/sgpt_0.0.2_Darwin_64bit.tar.gz"
      sha256 "2f1bcdad94d054a2e89ec9b504cecf34734f70224360bc3f71d031de927b37b9"

      def install
        bin.install "sgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hirosassa/sgpt/releases/download/v0.0.2/sgpt_0.0.2_Darwin_ARM64.tar.gz"
      sha256 "82d28a8910adce3c830b4296edda246bb5bb9d5d0fe3952349a1988c1d7c75fb"

      def install
        bin.install "sgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hirosassa/sgpt/releases/download/v0.0.2/sgpt_0.0.2_Linux_64bit.tar.gz"
        sha256 "4be131d59923ac02ea382883286b9689c08518d38194733b2865527926144d75"

        def install
          bin.install "sgpt"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hirosassa/sgpt/releases/download/v0.0.2/sgpt_0.0.2_Linux_ARM64.tar.gz"
        sha256 "a71d8a5701d617e41404e59dc1045ceecae6df6115b16c049d623ea3022b5c05"

        def install
          bin.install "sgpt"
        end
      end
    end
  end
end
