# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sgpt < Formula
  desc "Go clone of shell_gpt command. A command-line productivity tool powered by AI large language models (LLMs)."
  homepage "https://github.com/hirosassa/sgpt"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hirosassa/sgpt/releases/download/v0.0.1/sgpt_0.0.1_Darwin_64bit.tar.gz"
      sha256 "b6eb29092d4b838dea9c0982c3e9edba2a73d41426846959b1ef97b1d3fe0c15"

      def install
        bin.install "sgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hirosassa/sgpt/releases/download/v0.0.1/sgpt_0.0.1_Darwin_ARM64.tar.gz"
      sha256 "74a30e031470b031315bf9ae45f3a4af03bd7da073839250490e276f229079d2"

      def install
        bin.install "sgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hirosassa/sgpt/releases/download/v0.0.1/sgpt_0.0.1_Linux_64bit.tar.gz"
        sha256 "67d7b7b8fb3ad8f47740c905256009dc3b7e9467b70f083521c575b83bf80558"

        def install
          bin.install "sgpt"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hirosassa/sgpt/releases/download/v0.0.1/sgpt_0.0.1_Linux_ARM64.tar.gz"
        sha256 "560279a899adad0d62e410ec2cad8d888aa35e7d1993458a1eafc955691c441e"

        def install
          bin.install "sgpt"
        end
      end
    end
  end
end
